# Generated by Django 5.2.8 on 2025-12-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatmessage'),
        ('core', '0008_emailotp'),
    ]

    operations = [
    ]
